# Run code signing on merges to `main` to catch pipeline failures early, before a release.

name: Verify Code Signing

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: windows-latest
    outputs:
      version_tag: ${{ steps.meta.outputs.version_tag }}
    permissions:
      actions: write # For actions/upload-artifact
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          submodules: recursive

      - name: Build and test
        id: meta
        uses: ./.github/actions/build-and-test
        with:
          release-tag-input: ''
          run-tests: 'true'

      - name: Upload unsigned build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: unsigned-out
          path: ${{ github.workspace }}/out
          if-no-files-found: error

  sign-and-zip:
    needs: build-and-test
    if: github.event_name != 'pull_request'
    runs-on: windows-latest
    permissions:
      actions: read # For actions/download-artifact
      contents: read
      id-token: write # For .github/actions/azure-sign
    environment: verify-signing
    env:
      VERSION_TAG: ${{ needs.build-and-test.outputs.version_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          submodules: recursive

      - name: Download unsigned build artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: unsigned-out
          path: ${{ github.workspace }}/out

      - name: Azure login and sign build artifacts
        uses: ./.github/actions/azure-sign
        with:
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          signing-account-name: ${{ secrets.AZURE_SIGNING_ACCOUNT_NAME }}
          certificate-profile-name:
            ${{ secrets.AZURE_SIGNING_CERT_PROFILE_NAME }}

      # This step is not strictly necessary for signing, but it helps catch
      # pipeline failures earlier, before an actual release.
      - name: Collect artifacts and create ZIP bundles
        shell: pwsh
        run: ./.github/scripts/collect-artifacts-and-zip.ps1
